version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: chat_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat_network

  app:
    build: .
    container_name: chat_app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=chatdb
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
    networks:
      - chat_network

networks:
  chat_network:
    driver: bridge

volumes:
  postgres_data: